services:
  # client:
  #   container_name: dev_telegraph_client
  #   build: ./client
  #   image: telegraph_client
  #   ports:
  #     - 8080:8080
  #   working_dir: /code
  #   volumes:
  #     - type: bind
  #       source: ./client
  #       target: /code
  #   command: [ "http-server" ]
  api:
    container_name: telegraph_dev_api
    ports:
      - 3000:3000
    environment:
      - PGUSER=telegraph
      - PGHOST=db
      - PGPASSWORD=librarypass
      - PGDATABASE=library
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: telegraph_dev_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=telegraph
      - POSTGRES_PASSWORD=librarypass
volumes:
  dbdata:
networks:
  default:
    name: telegraph_api
